[project]
name = "home-work"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "p", email = "huyhuy094900@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "groq>=1.7.0",
    "pydantic>=2.13.5",
    "python-docx>=1.2.0",
    "python-dotenv>=1.2.3",
]
